rv-brand = "ReVanced Extended"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"

[YouTube]
version = "auto"
build-mode = "module"
exclusive-patches = true
included-patches = "'Ambient mode control' 'Change share sheet' 'Description components' 'Disable auto audio tracks' 'Disable auto captions' 'Disable resuming Shorts on startup' 'Enable external browser' 'Enable open links directly' 'Fullscreen components' 'Hide action buttons' 'Hide ads' 'Hide comments components' 'Hide feed components' 'Hide feed flyout menu' 'Hide layout components' 'Hide player buttons' 'Hide player flyout menu' 'Miniplayer' 'Navigation bar components' 'Player components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Sanitize sharing links' 'Seekbar components' 'Settings for YouTube' 'Shorts components' 'Toolbar components' 'Translations' 'Video playback' 'Visual preferences icons'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
